import { Activity } from "@prisma/client";

export const activities: Omit<Activity, "id" | "createdAt">[] = [
  {
    name: "Eiffel Tower Summit Tour",
    category: "SIGHTSEEING",
    description: "Guided tour to the very top of the Eiffel Tower with priority access.",
    location: "Paris, France",
    cost: 45,
    duration: 2.5,
  },
  {
    name: "Seine River Dinner Cruise",
    category: "FOOD",
    description: "Romantic dinner while cruising past illuminated Parisian landmarks.",
    location: "Paris, France",
    cost: 110,
    duration: 3,
  },
  {
    name: "Colosseum Underground Tour",
    category: "CULTURE",
    description: "Explore the restricted underground tunnels of the Roman Colosseum.",
    location: "Rome, Italy",
    cost: 65,
    duration: 3,
  },
  {
    name: "Trastevere Food Walk",
    category: "FOOD",
    description: "Sample the best pasta, gelato, and wine in Rome's charming Trastevere district.",
    location: "Rome, Italy",
    cost: 55,
    duration: 4,
  },
  {
    name: "Shibuya Crossing Photography",
    category: "SIGHTSEEING",
    description: "Best vantage points for shooting the world's busiest pedestrian crossing.",
    location: "Tokyo, Japan",
    cost: 0,
    duration: 1,
  },
  {
    name: "Tsukiji Outer Market Breakfast",
    category: "FOOD",
    description: "Early morning sushi and street food tour in the historic fish market area.",
    location: "Tokyo, Japan",
    cost: 40,
    duration: 2,
  },
  {
    name: "Fushimi Inari Shrine Hike",
    category: "ADVENTURE",
    description: "Hiking through thousands of vermilion torii gates up Mount Inari.",
    location: "Kyoto, Japan",
    cost: 0,
    duration: 3,
  },
  {
    name: "Traditional Tea Ceremony",
    category: "CULTURE",
    description: "Authentic matcha preparation and Zen ritual in a Gion tea house.",
    location: "Kyoto, Japan",
    cost: 35,
    duration: 1.5,
  },
  {
    name: "Ubud Jungle Swing",
    category: "ADVENTURE",
    description: "Thrilling swing over the rice terraces and tropical jungle.",
    location: "Ubud, Bali",
    cost: 20,
    duration: 1,
  },
  {
    name: "Tegalalang Rice Terrace Trek",
    category: "ADVENTURE",
    description: "Scenic walk through the world-famous Balinese rice fields.",
    location: "Ubud, Bali",
    cost: 5,
    duration: 2,
  },
  {
    name: "Potato Head Beach Club Sunset",
    category: "SOCIAL",
    description: "Signature cocktails and world-class DJs at Bali's most iconic beach club.",
    location: "Seminyak, Bali",
    cost: 30,
    duration: 4,
  },
  {
    name: "Balinese Massage & Spa",
    category: "WELLNESS",
    description: "Relaxing full body massage using traditional Balinese techniques.",
    location: "Seminyak, Bali",
    cost: 45,
    duration: 2,
  },
  {
    name: "Harajuku Street Style Tour",
    category: "SHOPPING",
    description: "Explore Takeshita Street and the quirky fashion boutiques of Harajuku.",
    location: "Tokyo, Japan",
    cost: 0,
    duration: 3,
  },
  {
    name: "Louvre Museum Highlights",
    category: "CULTURE",
    description: "Skip-the-line access to see the Mona Lisa and Venus de Milo.",
    location: "Paris, France",
    cost: 22,
    duration: 3,
  },
  {
    name: "Vatican Museums & Sistine Chapel",
    category: "CULTURE",
    description: "Vast collection of art and Michelangelo's masterpiece.",
    location: "Vatican City",
    cost: 30,
    duration: 4,
  },
  {
    name: "Mount Batur Sunrise Trek",
    category: "ADVENTURE",
    description: "Early morning hike to watch the sun rise over an active volcano.",
    location: "Kintamani, Bali",
    cost: 50,
    duration: 6,
  },
  {
    name: "Akihabara Electronic City",
    category: "SHOPPING",
    description: "Anime, manga, and the latest tech gadgets in the electric town.",
    location: "Tokyo, Japan",
    cost: 0,
    duration: 4,
  },
  {
    name: "Roman Forum Exploration",
    category: "CULTURE",
    description: "Walk through the ruins of the ancient Roman Empire's heart.",
    location: "Rome, Italy",
    cost: 16,
    duration: 2,
  },
  {
    name: "Montmartre Artist Square",
    category: "SIGHTSEEING",
    description: "Charming hilltop neighborhood with views over Paris and street artists.",
    location: "Paris, France",
    cost: 0,
    duration: 2,
  },
  {
    name: "Uluwatu Temple Fire Dance",
    category: "CULTURE",
    description: "Traditional Kecak dance performance on a cliff at sunset.",
    location: "Uluwatu, Bali",
    cost: 15,
    duration: 1.5,
  }
];
